-- ============================================================================
-- ONE MISSING INDEX: broker_directory.agency_id
--
-- 🔴 THIS FILE ORIGINALLY PROPOSED FOUR INDEXES AND THREE OF THEM ALREADY
-- EXISTED. The first version of this migration was written from `schema.sql`,
-- which declares eight indexes, none of them on the CRM tables -- and I
-- concluded there were none.
--
-- ⛔ `schema.sql` IS NOT THE SCHEMA. It defines exactly three tables (quotes,
-- commitments, aby_task). `agencies`, `people` and `broker_directory` are not
-- in it at all. THE LIVE SCHEMA IS A MIGRATION LIST INSIDE `worker.js`, and
-- that list creates 33 indexes, including:
--
--     agencies_parent              ON agencies (parent_id)
--     broker_directory_person      ON broker_directory (person_id)
--     agencies_lower_name          ON agencies (lower(trim(name)))
--     quotes_lower_broker_agency   ON quotes (lower(trim(broker_agency)))
--
-- So three of the four originally proposed here were already there, and the
-- claim that went with them -- that the quotes-to-agencies join reads ~9.5
-- million rows -- was WRONG. That join is written
-- `ON lower(trim(a.name)) = lower(trim(q.broker_agency))`, and BOTH sides
-- have a matching functional index.
--
-- WHAT SURVIVES, AND IT IS GENUINELY MISSING. `broker_directory.agency_id` was
-- added by `ALTER TABLE broker_directory ADD COLUMN agency_id` and never
-- indexed, while `broker_directory.person_id` -- added the same way -- was.
-- It is a join key: `LEFT JOIN agencies a ON a.id = d.agency_id` appears on
-- the brokers-and-agencies screens.
--
-- ⚠️ THIS IS NOT PRESENTED AS THE CAUSE OF THE 5,000,000-ROW DAY. One missing
-- index on a ~2,300-row table cannot read five million rows. The cause of that
-- is STILL UNKNOWN, and the honest next step is D1's own query statistics in
-- the Cloudflare dashboard -- Analytics for the database, which reports the
-- heaviest queries -- rather than more reading of the code.
--
-- SAFE TO RUN. CREATE INDEX adds no rows and changes no data; `IF NOT EXISTS`
-- makes a re-run a no-op; reversible with DROP INDEX.
--
-- ⚠️ RUN IT AFTER THE READ LIMIT RESETS (2026-09-02 00:00 UTC) OR AFTER
-- UPGRADING -- building an index reads the table.
--
-- HOW TO RUN:
--   npx wrangler d1 execute <database> --remote --file=scripts/2026-09-01-crm-indexes.sql
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_broker_directory_agency_id ON broker_directory (agency_id);
